api_app/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", home, name="api_page")
]

router = routers.SimpleRouter()

router.register('category', CategoryViewSet, basename='category')
router.register('tag', TagViewSet, basename='tag')
router.register('goods', GoodsViewSet, basename='goods')
router.register('client', ClientViewSet, basename='client')
router.register('order', OrderViewSet, basename='order')
router.register('ordergoods', OrderGoodsViewSet, basename='ordergoods')
router.register('basketgoods', BasketGoodsViewSet, basename='basketgoods')
urlpatterns += router.urls

practice_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    # Api page root
    path("api/", include('api_app.urls')),
    
    # Routing app root
    path("", include('routing_app.urls')),
    
    # Administration
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

routing_app/urls.py
from django.urls import path, include
from routing_app.views import *

urlpatterns = [
    
    # Users
    path("", index, name="home"),
    path("login/", login_user, name="login_page"),
    path("register/", register_user, name="register_page"),
    path("logout/", logout_user, name="logout_page"),
    
    
    # Catalogue rooot
    path("catalogue/", catalogue, name="catalogue_list"),
    path("catalogue/<int:pk>", catalogue_details, name="catalogue_detail"),
    path("catalogue/insert", CatalogueCreateView.as_view(), name="catalogue_insert"),
    path("catalogue/delete/<int:pk>", CatalogueDeleteView.as_view(), name="catalogue_delete"),
    path("catalogue/edit/<int:pk>", CatalogueUpdateView.as_view(), name="catalogue_edit"),
    path("catalogue/feedback", catalogue_feedback, name="feedback_page"),
    

    # Profile root
    path("profile/", profile, name="profile_page"),

    # Basket root
    path("basket/", basket, name="basket_page"),
    path("basket/delete/<int:pk>", BasketDeleteView.as_view(), name="basket_delete"),
    path("basket/clear", basket_clear, name="basket_clear"),
    path("basket/order", create_order, name="order_create"),
    
    # Orders root
    path("order/", orders, name="orders_page"),
    path("order/<uuid:pk>", order_details, name="order_details"),
    path("order/delete/<uuid:pk>", OrderDeleteView.as_view(), name="order_delete"),
    
    
    # Category root
    path("category/", CategoryListView.as_view(), name="category_list"),
    path("category/insert", CategoryCreateView.as_view(), name="category_insert"),
    path("category/edit/<int:pk>", CategoryUpdateView.as_view(), name="category_edit"),
    path("category/delete/<int:pk>", CategoryDeleteView.as_view(), name="category_delete"),
    
    # Tag root
    path("tag/", TagListView.as_view(), name="tag_list"),
    path("tag/insert", TagCreateView.as_view(), name="tag_insert"),
    path("tag/edit/<int:pk>", TagUpdateView.as_view(), name="tag_edit"),
    path("tag/delete/<int:pk>", TagDeleteView.as_view(), name="tag_delete")
]
    

routing_app/models.py
import uuid
import re
import random
from django.core.validators import RegexValidator
from django.db import models

class Item():
    def __init__(self, id):
        self.id = id
        self.name = 'Test name' + str(id)
        self.description = 'Test description' + str(id)
        self.description = 'Test description' + str(id)
        self.random_1 = random.randint(1, id + 1)
        self.random_2 = random.randint(id, id * 2 + 1)
        self.random_3 = random.randint(id-id*2-1, 0)
        
class Category(models.Model):
    name = models.CharField(verbose_name='name', max_length=255)
    
    description = models.TextField(null=True, blank=True, verbose_name='description')
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

class Tag(models.Model):
    name = models.CharField(verbose_name='name', max_length=255)
    
    description = models.TextField(null=True, blank=True, verbose_name='description')
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'

class Goods(models.Model):
    name = models.CharField(verbose_name='name', max_length=255)
    
    description = models.TextField(null=True, blank=True, verbose_name='description')
    
    price = models.FloatField(verbose_name='price', default=1.0)
    
    image = models.ImageField(verbose_name='image', upload_to='image/%Y/%m/%d', null=True, blank=True)
    
    dateCreated = models.DateTimeField(verbose_name='date_created', auto_now_add=True)
    
    dateEdited = models.DateTimeField(verbose_name='date_edited', auto_now=True)
    
    category = models.ForeignKey(Category, verbose_name='category', on_delete=models.CASCADE)
    
    tags = models.ManyToManyField(Tag, verbose_name='tags')
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'good'
        verbose_name_plural = 'goods'
        
class Client(models.Model):
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='id')
    
    login=models.CharField(verbose_name='login', max_length=255)
    
    password=models.TextField(verbose_name='password', null=False, blank=False)
    
    salt=models.CharField(verbose_name='salt', max_length=200)
    
    firstName = models.CharField(verbose_name='first_name', max_length=255)
    
    lastName = models.CharField(verbose_name='last_name', max_length=255)
    
    email = models.CharField(verbose_name='email_address', max_length=50, null=True, validators=[
        RegexValidator(
            regex=r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}',
            message="Enter a valid phone number",
            code="invalid_phone",
        )])
    
    
    
    def __str__(self):
        return f'{self.firstName} {self.lastName}'
    
    
    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients',

class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='id')
    
    deliveryAddress = models.TextField(verbose_name='delivery_address')
    
    dateCreated = models.DateTimeField(verbose_name='date_created', auto_now=False, auto_now_add=True)
    
    client = models.ForeignKey(Client, verbose_name='client', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'order'
        verbose_name_plural = 'orders'

class OrderGoods(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='id')
    
    order = models.ForeignKey(Order, verbose_name='order', on_delete=models.CASCADE)
    
    good = models.ForeignKey(Goods, verbose_name='good', on_delete=models.CASCADE)
    
    amount = models.PositiveIntegerField(verbose_name='amount_good', default=1)
    
    discount=models.FloatField(verbose_name='discount_per_unit', default = 0.0)
    
    class Meta:
        verbose_name = 'order_good'
        verbose_name_plural = 'order_goods'  
        
class BasketGoods(models.Model):
    client = models.ForeignKey(Client, verbose_name='client', on_delete=models.CASCADE)
    
    good = models.ForeignKey(Goods, verbose_name='good', on_delete=models.CASCADE)
    
    amount = models.PositiveIntegerField(verbose_name='amount_good', default=1)
    
    discount=models.FloatField(verbose_name='discount_per_unit', default = 0.0)
    
    def __str__(self):
        return f'{client.__str__()} - {good.__str__()}'
    
    
    class Meta:
        verbose_name = 'basket_goods'
        verbose_name_plural = 'basket_goods'
        
class FavoriteGoods(models.Model):
    client = models.ForeignKey(Client, verbose_name='client', on_delete=models.CASCADE)
    
    good = models.ForeignKey(Goods, verbose_name='good', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Favorite: {client.__str__()} - {good.__str__()}'
    
    class Meta:
        verbose_name = 'favorite_goods'
        verbose_name_plural = 'favorites_goods'

routing_app/forms.py
from .models import *
from django.forms import ModelForm, HiddenInput, CharField, TextInput, EmailInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class GoodsForm(ModelForm):
    class Meta:
        model = Goods
        fields = ("name", "description", "price", "image", "category", "tags")
        
class BasketGoodsForm(ModelForm):
    
    class Meta:
        model = BasketGoods
        fields = ("client", "good", "amount", "discount")
        widgets = {
            'good': HiddenInput(),
            'client': HiddenInput(),
            'discount': HiddenInput(),
        }

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ("deliveryAddress", "client")
        widgets = {
            "client": HiddenInput(),
        }

        
class ProfileForm(ModelForm):
    
    class Meta:
        model = Client
        fields = ("login", "password", "salt", "firstName", "lastName", "email")
        widgets = {
            'salt': HiddenInput(),
        }

class CategoryForm(ModelForm):
    
    class Meta:
        model = Category
        fields = ("name", "description")

class TagForm(ModelForm):
    
    class Meta:
        model = Tag
        fields = ("name", "description")

class RegistrationForm(UserCreationForm):
    username = CharField(
        label = "User login",
        widget = TextInput(attrs={"class":"form-control", }),
        min_length=5
    )
    
    first_name = CharField(
        label="First name",
        widget = TextInput(attrs={"class":"form-control", }),
        max_length=255
    )
    
    last_name = CharField(
        label="Last name",
        widget = TextInput(attrs={"class":"form-control", }),
        max_length=255
    )
    
    email = CharField(
        label = "Email address",
        widget = EmailInput(attrs={"class":"form-control", }),
    )
    
    password1 = CharField(
        label = "Password",
        widget=PasswordInput(attrs={"class":"form-control", })
    )
    
    password2 = CharField(
        label = "Повторите пароль",
        widget=PasswordInput(attrs={"class":"form-control", })
    )
    
    class Meta:
        model=User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]
    
class LoginForm(AuthenticationForm):
    username = CharField(
        label = "User login",
        widget = TextInput(attrs={"class":"form-control", }),
        min_length=5
    )
    
    password1 = CharField(
        label = "Password",
        widget=PasswordInput(attrs={"class":"form-control", })
    )

routing_app/templates/orders/order_confirm_delete.html
{% extends "base.html" %}
{% block title %}delete order {{item.id}}{% endblock %}
{% block body %}
    <div>
        <dl class="dl-horizontal">
        	<dt>Order</dt>
        	<dd>
                {{order.id}}
        	</dd>
            
        	<dt>Date created</dt>
        	<dd>
                {{item.dateCreated}}
        	</dd>

        	<dt>Delivery address</dt>
        	<dd>
                {{item.deliveryAddress}}
        	</dd>
        </dl>

    	<div class="row">
    		<form method="post" class="col-md-4">
    			<div class="form-group">
                    {% csrf_token %}
    				<input type="submit" class="btn btn-danger" value="Delete" />
    			</div>
    		</form>
            <a href="{% url "basket_page" %}" class="col-md-4">Go back</a>
    	</div>
    </div>
{% endblock %}

{% block nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block catalogue_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/orders/order_details.html
{% extends "base.html" %}
{% block title %}Order details{% endblock %}
{% block body %}
      <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-10 col-xl-8">
        <div class="card" style="border-radius: 10px;">
          <div class="card-header px-4 py-5">
            <h5 class="text-muted mb-0">Thanks for your Order, <span style="color: #a8729a;">{{user.last_name}} {{user.first_name}}</span>!</h5>
          </div>
          <div class="card-body p-4">
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-normal mb-0" style="color: #a8729a;">Receipt</p>
              <p class="small text-muted mb-0">Receipt Voucher : {{order.id}}</p>
            </div>
            {% if perms.routing_app.view_ordergoods %}
              {% for orderGood in order_goods %}
              <div class="card shadow-0 border mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-2">
                      <img src="{{orderGood.good.image.url}}" alt="{{orderGood.good.name}}" class="img-fluid rounded mx-auto d-block">
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0">{{orderGood.good.name}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">{{orderGood.good.category}}</p>
                    </div>
                    <div class="col-md-4">
                        {% for tag in orderGood.good.tags.all %}
                        <div class="row-md-2 text-center d-flex justify-content-center align-items-center">
                            <p class="text-muted mb-0 small">{{tag}}</p>
                          </div>
                          {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            {% endif %}

            <div class="d-flex justify-content-between pt-2">
              <p class="fw-bold mb-0">Order Details</p>
              <p class="text-muted mb-0"><span class="fw-bold me-4">Total</span> {{total_sum}}</p>
            </div>

            <div class="d-flex justify-content-between">
              <p class="text-muted mb-0">Invoice Date : {{order.dateCreated}}</p>
            </div>

            <div class="d-flex justify-content-between mb-5">
              <p class="text-muted mb-0"><span class="fw-bold me-4">Delivery:</span> {{order.deliveryAddress}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block nav %}{% endblock %}
{% block catalogue_nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/orders/orders.html
{% extends "base.html" %}
{% block title %}Orders{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
        {% for item in list_items %}
            <div class="card col-md-4">
                <div class="container">
                    <h4><b>Item {{item.id}}</b></h4>
                    <p>Client: {{item.client}}</p>
                    <p>Date created: {{item.dateCreated}}</p>
                    <p>Delivery address: <b>{{item.deliveryAddress}}</b></p>
                    <div class="row">
                        <a href="{% url "order_details" item.pk %}" class="btn btn-secondary col-md-4">Details</a>
                        <a href="" class="btn btn-primary col-md-4">Edit</a>
                        <a href="{% url "order_delete" item.pk %}" class="btn btn-danger col-md-4">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}
{% block nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}