api_app/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", home, name="api_page")
]

router = routers.SimpleRouter()

router.register('category', CategoryViewSet, basename='category')
router.register('tag', TagViewSet, basename='tag')
router.register('goods', GoodsViewSet, basename='goods')
router.register('client', ClientViewSet, basename='client')
router.register('order', OrderViewSet, basename='order')
router.register('ordergoods', OrderGoodsViewSet, basename='ordergoods')
router.register('basketgoods', BasketGoodsViewSet, basename='basketgoods')
urlpatterns += router.urls

practice_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    # Api page root
    path("api/", include('api_app.urls')),
    
    # Routing app root
    path("", include('routing_app.urls')),
    
    # Administration
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

routing_app/urls.py
from django.urls import path, include
from routing_app.views import *

urlpatterns = [
    
    # Users
    path("", index, name="home"),
    path("login/", login_user, name="login_page"),
    path("register/", register_user, name="register_page"),
    path("logout/", logout_user, name="logout_page"),
    
    
    # Catalogue rooot
    path("catalogue/", catalogue, name="catalogue_list"),
    path("catalogue/<int:pk>", catalogue_details, name="catalogue_detail"),
    path("catalogue/insert", CatalogueCreateView.as_view(), name="catalogue_insert"),
    path("catalogue/delete/<int:pk>", CatalogueDeleteView.as_view(), name="catalogue_delete"),
    path("catalogue/edit/<int:pk>", CatalogueUpdateView.as_view(), name="catalogue_edit"),
    path("catalogue/feedback", catalogue_feedback, name="feedback_page"),
    

    # Profile root
    path("profile/", profile, name="profile_page"),

    # Basket root
    path("basket/", basket, name="basket_page"),
    path("basket/delete/<int:pk>", BasketDeleteView.as_view(), name="basket_delete"),
    path("basket/clear", basket_clear, name="basket_clear"),
    path("basket/order", create_order, name="order_create"),
    
    # Orders root
    path("order/", orders, name="orders_page"),
    path("order/<uuid:pk>", order_details, name="order_details"),
    path("order/delete/<uuid:pk>", OrderDeleteView.as_view(), name="order_delete"),
    
    
    # Category root
    path("category/", CategoryListView.as_view(), name="category_list"),
    path("category/insert", CategoryCreateView.as_view(), name="category_insert"),
    path("category/edit/<int:pk>", CategoryUpdateView.as_view(), name="category_edit"),
    path("category/delete/<int:pk>", CategoryDeleteView.as_view(), name="category_delete"),
    
    # Tag root
    path("tag/", TagListView.as_view(), name="tag_list"),
    path("tag/insert", TagCreateView.as_view(), name="tag_insert"),
    path("tag/edit/<int:pk>", TagUpdateView.as_view(), name="tag_edit"),
    path("tag/delete/<int:pk>", TagDeleteView.as_view(), name="tag_delete")
]
    

routing_app/models.py
import uuid
import re
import random
from django.core.validators import RegexValidator
from django.db import models

class Item():
    def __init__(self, id):
        self.id = id
        self.name = 'Test name' + str(id)
        self.description = 'Test description' + str(id)
        self.description = 'Test description' + str(id)
        self.random_1 = random.randint(1, id + 1)
        self.random_2 = random.randint(id, id * 2 + 1)
        self.random_3 = random.randint(id-id*2-1, 0)
        
class Category(models.Model):
    name = models.CharField(verbose_name='name', max_length=255)
    
    description = models.TextField(null=True, blank=True, verbose_name='description')
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

class Tag(models.Model):
    name = models.CharField(verbose_name='name', max_length=255)
    
    description = models.TextField(null=True, blank=True, verbose_name='description')
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'

class Goods(models.Model):
    name = models.CharField(verbose_name='name', max_length=255)
    
    description = models.TextField(null=True, blank=True, verbose_name='description')
    
    price = models.FloatField(verbose_name='price', default=1.0)
    
    image = models.ImageField(verbose_name='image', upload_to='image/%Y/%m/%d', null=True, blank=True)
    
    dateCreated = models.DateTimeField(verbose_name='date_created', auto_now_add=True)
    
    dateEdited = models.DateTimeField(verbose_name='date_edited', auto_now=True)
    
    category = models.ForeignKey(Category, verbose_name='category', on_delete=models.CASCADE)
    
    tags = models.ManyToManyField(Tag, verbose_name='tags')
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'good'
        verbose_name_plural = 'goods'
        
class Client(models.Model):
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='id')
    
    login=models.CharField(verbose_name='login', max_length=255)
    
    password=models.TextField(verbose_name='password', null=False, blank=False)
    
    salt=models.CharField(verbose_name='salt', max_length=200)
    
    firstName = models.CharField(verbose_name='first_name', max_length=255)
    
    lastName = models.CharField(verbose_name='last_name', max_length=255)
    
    email = models.CharField(verbose_name='email_address', max_length=50, null=True, validators=[
        RegexValidator(
            regex=r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}',
            message="Enter a valid phone number",
            code="invalid_phone",
        )])
    
    
    
    def __str__(self):
        return f'{self.firstName} {self.lastName}'
    
    
    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients',

class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='id')
    
    deliveryAddress = models.TextField(verbose_name='delivery_address')
    
    dateCreated = models.DateTimeField(verbose_name='date_created', auto_now=False, auto_now_add=True)
    
    client = models.ForeignKey(Client, verbose_name='client', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'order'
        verbose_name_plural = 'orders'

class OrderGoods(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='id')
    
    order = models.ForeignKey(Order, verbose_name='order', on_delete=models.CASCADE)
    
    good = models.ForeignKey(Goods, verbose_name='good', on_delete=models.CASCADE)
    
    amount = models.PositiveIntegerField(verbose_name='amount_good', default=1)
    
    discount=models.FloatField(verbose_name='discount_per_unit', default = 0.0)
    
    class Meta:
        verbose_name = 'order_good'
        verbose_name_plural = 'order_goods'  
        
class BasketGoods(models.Model):
    client = models.ForeignKey(Client, verbose_name='client', on_delete=models.CASCADE)
    
    good = models.ForeignKey(Goods, verbose_name='good', on_delete=models.CASCADE)
    
    amount = models.PositiveIntegerField(verbose_name='amount_good', default=1)
    
    discount=models.FloatField(verbose_name='discount_per_unit', default = 0.0)
    
    def __str__(self):
        return f'{client.__str__()} - {good.__str__()}'
    
    
    class Meta:
        verbose_name = 'basket_goods'
        verbose_name_plural = 'basket_goods'
        
class FavoriteGoods(models.Model):
    client = models.ForeignKey(Client, verbose_name='client', on_delete=models.CASCADE)
    
    good = models.ForeignKey(Goods, verbose_name='good', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Favorite: {client.__str__()} - {good.__str__()}'
    
    class Meta:
        verbose_name = 'favorite_goods'
        verbose_name_plural = 'favorites_goods'

routing_app/forms.py
from .models import *
from django.forms import ModelForm, HiddenInput, CharField, TextInput, EmailInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class GoodsForm(ModelForm):
    class Meta:
        model = Goods
        fields = ("name", "description", "price", "image", "category", "tags")
        
class BasketGoodsForm(ModelForm):
    
    class Meta:
        model = BasketGoods
        fields = ("client", "good", "amount", "discount")
        widgets = {
            'good': HiddenInput(),
            'client': HiddenInput(),
            'discount': HiddenInput(),
        }

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ("deliveryAddress", "client")
        widgets = {
            "client": HiddenInput(),
        }

        
class ProfileForm(ModelForm):
    
    class Meta:
        model = Client
        fields = ("login", "password", "salt", "firstName", "lastName", "email")
        widgets = {
            'salt': HiddenInput(),
        }

class CategoryForm(ModelForm):
    
    class Meta:
        model = Category
        fields = ("name", "description")

class TagForm(ModelForm):
    
    class Meta:
        model = Tag
        fields = ("name", "description")

class RegistrationForm(UserCreationForm):
    username = CharField(
        label = "User login",
        widget = TextInput(attrs={"class":"form-control", }),
        min_length=5
    )
    
    first_name = CharField(
        label="First name",
        widget = TextInput(attrs={"class":"form-control", }),
        max_length=255
    )
    
    last_name = CharField(
        label="Last name",
        widget = TextInput(attrs={"class":"form-control", }),
        max_length=255
    )
    
    email = CharField(
        label = "Email address",
        widget = EmailInput(attrs={"class":"form-control", }),
    )
    
    password1 = CharField(
        label = "Password",
        widget=PasswordInput(attrs={"class":"form-control", })
    )
    
    password2 = CharField(
        label = "Повторите пароль",
        widget=PasswordInput(attrs={"class":"form-control", })
    )
    
    class Meta:
        model=User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]
    
class LoginForm(AuthenticationForm):
    username = CharField(
        label = "User login",
        widget = TextInput(attrs={"class":"form-control", }),
        min_length=5
    )
    
    password1 = CharField(
        label = "Password",
        widget=PasswordInput(attrs={"class":"form-control", })
    )

routing_app/templates/routing_practice/catalogue.html
{% extends "base.html" %}
{% block title %}Catalogue{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
        {% for item in list_items %}
            <div class="card col-md-4">
                {% if item.image %}
                <img src="{{item.image.url}}" alt="{{item.name}}" class="img-thumbnail rounded mx-auto d-block">
                {% else %}
                {%load static%}
                <img src="{% static 'img/img_avatar.png' %}" alt="pic" class="img-thumbnail rounded mx-auto d-block">
                {% endif %}
                <div class="container">
                    <h4><b>Item {{item.id}}</b></h4>
                    <p>Name: {{item.name}}</p>
                    <p>Description: {{item.description}}</p>
                    <p>Price: <b>{{item.price}}</b></p>
                    <div class="row">
                        <a href="/catalogue/{{item.id}}" class="btn btn-secondary col-md-4">Details</a>
                        <a href="/catalogue/edit/{{item.id}}" class="btn btn-primary col-md-4">Edit</a>
                        <a href="/catalogue/delete/{{item.id}}" class="btn btn-danger col-md-4">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}
{% block nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/routing_practice/catalogue_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete item {{item}}{% endblock %}
{% block body %}
    <div>
        <dl class="dl-horizontal">
        	<dt>Name</dt>
        	<dd>
                {{item.name}}
        	</dd>
        
        	<dt>Description</dt>
        	<dd>
                {{item.description}}
        	</dd>
        
        	<dt>Price</dt>
        	<dd>
                {{item.price}}
        	</dd>
        </dl>

    	<div class="row">
    		<form method="post" class="col-md-4">
    			<div class="form-group">
                    {% csrf_token %}
    				<input type="submit" class="btn btn-danger" value="Delete" />
    			</div>
    		</form>
            <a href="/catalogue" class="col-md-4">Go back</a>
    	</div>
    </div>
{% endblock %}

{% block nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/routing_practice/catalogue_detail.html
{% extends "base.html" %}
{% block title %}Item {{item}}{% endblock %}
{% block body %}
    <div class="container mt-5">
        <div class="row">
            <!-- Product Images -->
            <div class="col-md-6 mb-4">
                {% if item.image %}
                <img src="{{item.image.url}}" alt="{{item.name}}" class="img-thumbnail rounded mx-auto d-block">
                {% else %}
                {%load static%}
                <img src="{% static 'img/img_avatar.png' %}" alt="pic" class="img-thumbnail rounded mx-auto d-block">
                {% endif %}
            </div>
        
            <!-- Product Details -->
            <div class="col-md-6">
                <h2 class="mb-3">{{item.name}}</h2>
                <p class="mb-4">{{item.description}}</p>
                <div class="mb-4">
                    <h5>Tags:</h5>
                    <div class="row" role="group">
                        {%for tag in item.tags.all %}
                            <a href="{% url "catalogue_list" %}?tag={{tag}}" class="btn-default col-md-2">{{tag}}</a>
                        {%endfor%}
                    </div>
                </div>
                <div class="mb-4">
                    <h5>Category:</h5>
                        <a href="{% url "catalogue_list" %}?category={{item.category}}">{{item.category}}</a>
                    </div>
                </div>
                <a href="{% url "catalogue_edit" item.pk %}" class="btn btn-outline-secondary btn-lg mb-3">
                        <i class="bi bi-pencil"></i> Edit
                </a>
                <a href="{% url "catalogue_delete" item.pk %}" class="btn btn-danger btn-lg mb-3">
                        <i class="bi bi-trash"></i> Delete
                </a>
                {% if perms.routing_app.add_basketgoods %}
                <form method="POST">
                    {% csrf_token %}
                    {{ basket_form.as_div }}
                    <div class="form-group">
                        <input type="submit" value="Send" class="btn btn-success" />
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/routing_practice/catalogue_feedback.html
{% extends "base.html" %}
{% block title %}Feedback{% endblock %}
{% block body %}
    <form>
        <div class="form-group">
            <label for="uname">
                Name
            </label>
            
            <input type="text" id="uname" 
            name="uname" required>
        </div>

        <div class="form-group">
            <label for="email">
                Email Address
            </label>
            <input type="email" id="email" 
            name="email" required>
        </div>
                
        <div class="form-group">
            <label for="phone">
                Phone No
            </label>
            <input type="tel" id="phone" 
            name="phone" required>
        </div>

        <div class="form-group">
            <label>
                Do you satisfy with our service?
            </label>
            <div class="radio-group">
                <input type="radio" id="yes" 
                name="satisfy" value="yes" checked>
                <label for="yes">Yes</label>
                
                <input type="radio" id="no" 
                name="satisfy" value="no">
                <label for="no">No</label>
            </div>
        </div>

        <div class="form-group">
            <label for="msg">
                Write your Suggestions:
            </label>
            <textarea id="msg" name="msg" 
            rows="4" cols="10" required>
            </textarea>
        </div>
        <button type="submit" class="btn btn-success">
            Submit
        </button>
    </form>
{% endblock %}

{% block catalogue_nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/routing_practice/catalogue_insert.html
{% extends "base.html" %}
{% block title %}Insert item{% endblock %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" />
        </div>
    </form>
{% endblock %}

{% block nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}

routing_app/templates/routing_practice/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block body %}
    <div class="container rounded bg-white mt-5 mb-5">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" />
        </div>
        </form>
    </div>
{% endblock %}

{% block catalogue_nav %}{% endblock %}
{% block categories_nav %}{% endblock %}
{% block tags_nav %}{% endblock %}